# Layout
max_width = 120
tab_spaces = 4
hard_tabs = true
# indent_style = "Visual"

# Imports
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
reorder_imports = true

# Wrapping
use_small_heuristics = "Default"
# trailing_comma = "Always"

# Cleanup
# blank_lines_upper_bound = 1
remove_nested_parens = true